import { PrimeReactProvider } from 'primereact/api';
import 'primeicons/primeicons.css';
import 'primereact/resources/themes/lara-light-green/theme.css';
import './globals.css';
import { fontMontserrat } from '@/fonts';
import CartProvider from '@/context/cart';
import { pageName } from '@/data';

export const metadata = {
  title: pageName,
  // description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const value = {
    appendTo: 'self',
  };

  return (
    <html lang='en' className='scroll-smooth'>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              const style = document.createElement('style')
              style.innerHTML = '@layer tailwind-base, primereact, tailwind-utilities;'
              style.setAttribute('type', 'text/css')
              document.querySelector('head').prepend(style)
            `,
          }}
        />
      </head>
      <body className={`${fontMontserrat.variable} font-montserrat`}>
        <PrimeReactProvider value={value}>
          <CartProvider>{children}</CartProvider>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
